Fix the filename of .msi file generated by bdist_msi.
marcelotduarte/cx_Freeze pull request #1591
Opened 2022-08-20 19:11 UTC by cainesi

Fix so that if a specific .msi filename is provided by the --target-name option on the bdist_msi command, then that name will be used without alternation.

2022-08-20 20:05 UTC, marcelotduarte requested changes

2022-08-20 20:05 UTC, marcelotduarte commented on cx_Freeze/command/bdist_msi.py
> +        if self.target_name is not None:
You could create an 'else' next to 'if self.target_name is None' and maybe avoid this new variable msi_name.

2022-08-21 01:26 UTC, cainesi commented on cx_Freeze/command/bdist_msi.py
> +        if self.target_name is not None:
I thought about that, but I could not see a way to do it without making other changes.  The problem is that once you get down to the run() function, you would need to know whether self.target_name was a specific name provided by the user (to be used unchanged) or something cx_freeze is generating (in which case we apparently want to add the platform name).

2022-08-21 03:57 UTC, marcelotduarte requested changes

2022-08-21 03:57 UTC, marcelotduarte commented on cx_Freeze/command/bdist_msi.py
> +        if self.target_name is not None:
Then, I think that a few lines down, at:
self.fullname = f"{name}-{version}"
can be changed to 
```
if os.path.splitext(name)[1].lower() == ".msi":
    self.fullname = name
else:
    self.fullname = f"{name}-{version}"
```

2022-08-21 03:57 UTC, marcelotduarte commented on cx_Freeze/command/bdist_msi.py
> +        if self.msi_name is not None:
And here:
```
if os.path.splitext(self.target_name)[1].lower() == ".msi":
    msi_name = self.target_name
else:
    # the previous if (with base_name changed to msi_name) to be more descriptive.
```

2022-08-21 03:57 UTC, marcelotduarte commented on cx_Freeze/command/bdist_msi.py
> +        if self.target_name is not None:
fullname is common variable used in the build/bdist commands.

2022-08-21 16:39 UTC, cainesi commented
Looking at the code, I'm not sure I 100% under stand how it works, and don't want to break anything.

Right now, it looks like target_name is used for a two things that are not really necessarily (naming the msi file, the product name in the msi database)?  Could those be separated?

Is there a reason we could not put all the code for determining the msi name in one place? Instead of having is spread over finalize_options() and run()?  I particularly think having two widely separated uses of os.path.splitext(string)[1].lower() == ".msi" is going to lead to confusion.

Also, does target_version do anything other than changing the name of the msi file?

2022-10-15 18:10 UTC, cainesi commented on cx_Freeze/command/bdist_msi.py
> +        if self.msi_name is not None:
That works. I made that change.

2022-10-16 02:25 UTC, marcelotduarte approved these changes

2022-10-16 02:25 UTC, marcelotduarte commented
Thanks!

2022-10-16 02:26 UTC, merged

2022-10-16 04:01 UTC, marcelotduarte commented
@cainesi Can you add a test?
In this file: https://github.com/marcelotduarte/cx_Freeze/blob/main/tests/test_command_bdist_msi.py#L46

2022-10-16 04:05 UTC, cainesi commented
Sure. Will do.

2022-10-16 06:00 UTC, cainesi commented
#1648 adds a test.